/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empiricalanalysis;

import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author prathyusha
 */
public class AnalyticsData extends javax.swing.JFrame {

    /**
     * Creates new form AnalyticsData
     */
    public AnalyticsData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Get Analytics");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         EmpiricalAnalysis emp = new EmpiricalAnalysis();
        try {
            //start the analysis
            emp.start();
            //data for each size of matrix multiplied traditionally
            Map<Integer, Long> tmap = emp.getTradmap();
            //System.out.println("tmap" + tmap.size());

            //data for each size of matrix multiplied using original strassen
            Map<Integer, Long> pureStrasmap = emp.getPureStrasmap();
            //System.out.println("pireStmap" + pureStrasmap.size());

            //all maps of diffrent breakpoints tested against all sizes of matrix
            //for first chart
            List<Map> outlist = emp.getMaplist();
            
            
            XYSeriesCollection dataset1 = new XYSeriesCollection();
            XYSeries series1 = new XYSeries("Traditional");
            XYSeries series2 = new XYSeries("Pure Strassen");
            for (Map.Entry<Integer, Long> map : tmap.entrySet()) {
                series1.add(map.getKey(), map.getValue());
            }
            for (Map.Entry<Integer, Long> map : pureStrasmap.entrySet()) {
                series2.add(map.getKey(), map.getValue());
            }
            dataset1.addSeries(series1);
            dataset1.addSeries(series2);
            
            
            
            
            
          XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries[] serieslist = new XYSeries[10];
        int breappoint = 16;
        for (int i = 0; i < outlist.size(); i++) {
            if (i == 0) {
                serieslist[i] = new XYSeries("Trad");

            } else {
                serieslist[i] = new XYSeries("BP " + breappoint);
                breappoint *= 2;
            }
            Map<Integer, Long> outmap = outlist.get(i);
            for (Map.Entry<Integer, Long> map : outmap.entrySet()) {
                serieslist[i].add(map.getKey(), map.getValue());
            }
            dataset.addSeries(serieslist[i]);

        }
        
         XYLineChartExample xs = new XYLineChartExample();
         
            
           
            DefaultCategoryDataset defaultCategoryDatSet = new DefaultCategoryDataset();
            DefaultCategoryDataset defaultCategoryDatSetNew = new DefaultCategoryDataset();
            
            DefaultCategoryDataset defaultCategoryDatSetNewest = new DefaultCategoryDataset();
            DefaultCategoryDataset defaultCategoryDatSetNewestTwo = new DefaultCategoryDataset();
              
            TreeMap<Integer, Long> sorted = new TreeMap<>(); 
  
        // Copy all data from hashMap into TreeMap 
            sorted.putAll(tmap); 

            TreeMap<Integer, Long> sortedS = new TreeMap<>(); 

            sortedS.putAll(pureStrasmap); 
  
       
            for (Map.Entry<Integer, Long> map : sorted.entrySet()) {
             
                 defaultCategoryDatSet.addValue(map.getValue(), "Traditional", map.getKey());
                 defaultCategoryDatSetNew.addValue(pureStrasmap.get(map.getKey()), "Strassen", map.getKey());
               
            }
            
             JFreeChart jFreeChart = ChartFactory.createBarChart3D("Traditional","Matrix Size","Time in ms", defaultCategoryDatSet,PlotOrientation.VERTICAL,true, true, true);
            CategoryPlot P = jFreeChart.getCategoryPlot();
            P.setRangeGridlinePaint(Color.BLACK);
            
             JFreeChart jFreeChartNew = ChartFactory.createBarChart3D("Strassen","Matrix Size","Time in ms", defaultCategoryDatSetNew,PlotOrientation.VERTICAL,true, true, true);
          
            
            JFrame frameNew = new JFrame("Traditional Vs Strassen Analysis");
            frameNew.setLayout( new FlowLayout() );

           
            frameNew.getContentPane().add(new ChartPanel(jFreeChart));

            
            frameNew.getContentPane().add(new ChartPanel(jFreeChartNew));
            
            frameNew.getContentPane().add(new ChartPanel(xs.createChartTest(dataset)));
             frameNew.getContentPane().add(new ChartPanel(xs.createChartTest(dataset1)));

            frameNew.pack();

            frameNew.setVisible(true);
            
            
            
         

        } catch (FileNotFoundException ex) {
            Logger.getLogger(OutputChart.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
              
    }//GEN-LAST:event_jButton1ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalyticsData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalyticsData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalyticsData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalyticsData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalyticsData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
